name: "Build"

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Fetch SDK
        run: curl -sL --output MacOSX10.10.sdk.tar.xz ${{ secrets.SDK_URL }}

      - name: Build
        run: make build
