name: "Release"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Fetch SDK
        run: curl -sL --output MacOSX10.10.sdk.tar.xz ${{ secrets.SDK_URL }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release
        run: version="$(head -1 Dockerfile | awk -F':' '{print $2}')-${GITHUB_RUN_NUMBER}" make install
